image: node:latest

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn

stages:
  - test
  - lint
  - build

e2e:
  stage: test
  script:
    - npm run e2e

lint:
  stage: lint
  script:
    - npm run lint
