image: node:latest

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn

stages:
  - test
  - lint
  - build

e2e:
  stage: test
  script:
    - apt-get -qq update
    - apt-get -qq install -y libgtk2.0-0 libgconf-2-4 libasound2 libxtst6 libxss1 libnss3 xvfb
    - export DISPLAY=:99.0
    - start-stop-daemon --start --quiet --pidfile /var/run/xvfb.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1024x768x24 -fbdir /var/run -ac
    - npm run e2e

lint:
  stage: lint
  script:
    - npm run lint

