image: node:latest

before_script:
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn

stages:
  - test
  - lint
  - build

e2e:
  stage: test
  script:
    - npm run e2e

lint:
  stage: lint
  script:
    - npm run lint
